target_dir: /home/taw/binaries

perms:
  user: taw
  group: taw

types:
  binary: binary
  zip: zip
  tar_gz: tar.gz
  tar_xz: tar.xz

binaries:
  - name: k3d
    url: https://github.com/k3d-io/k3d/releases/download/v{version}/k3d-linux-amd64
    type: binary
    override: False
    strip: None
    inBin: False
    latest: 5.4.8
    versions:
      - version: 5.4.8
  - name: kubectl
    url: https://dl.k8s.io/release/v{version}/bin/linux/amd64/kubectl
    type: binary
    override: False
    strip: None
    inBin: False
    latest: 1.26.3
    versions:
      - version: 1.26.3
  - name: terragrunt
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v{version}/terragrunt_linux_amd64
    type: binary
    override: False
    strip: None
    inBin: False
    latest: 0.44.5
    versions:
      - version: 0.44.5
  - name: okd
    url: https://github.com/seemscloud/okd-cli/archive/refs/tags/okd-cli-{version}.tar.gz
    type: tar.gz
    override: False
    strip: True
    inBin: False
    latest: 3.11+4.10+4.11
    versions:
      - version: 3.11+4.10+4.11
  - name: helm
    url: https://get.helm.sh/helm-v{version}-linux-amd64.tar.gz
    type: tar.gz
    override: False
    strip: True
    inBin: False
    latest: 3.11.2
    versions:
      - version: 3.11.2
  - name: kustomize
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{version}/kustomize_v{version}_linux_amd64.tar.gz
    type: tar.gz
    override: False
    strip: False
    inBin: False
    latest: 4.5.7
    versions:
      - version: 4.5.7
  - name: node
    url: https://nodejs.org/dist/v{version}/node-v{version}-linux-x64.tar.xz
    type: tar.xz
    override: False
    strip: True
    inBin: True
    latest: 18.15.0
    versions:
      - version: 18.15.0
  - name: yarn
    url: https://github.com/yarnpkg/yarn/releases/download/v{version}/yarn-v{version}.tar.gz
    type: tar.gz
    override: False
    strip: True
    inBin: True
    latest: 1.22.19
    versions:
      - version: 1.22.19
  - name: terraform
    url: https://releases.hashicorp.com/terraform/{version}/terraform_{version}_linux_amd64.zip
    type: zip
    override: False
    strip: False
    inBin: False
    latest: 1.4.3
    versions:
      - version: 1.4.3
  - name: upx
    url: https://github.com/upx/upx/releases/download/v{version}/upx-{version}-amd64_linux.tar.xz
    type: tar.xz
    override: False
    strip: True
    inBin: False
    latest: 4.0.1
    versions:
      - version: 4.0.1
  - name: go
    url: https://go.dev/dl/go{version}.linux-amd64.tar.gz
    type: tar.gz
    override: False
    strip: True
    inBin: True
    latest: 1.20.4
    versions:
      - version: 1.20.4
  - name: groovy
    url: https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-{version}.zip
    type: zip
    override: False
    strip: True
    inBin: True
    latest: 4.0.13
    versions:
      - version: 4.0.13
      - version: 3.0.18
      - version: 2.5.22
  - name: yq
    url: https://github.com/mikefarah/yq/releases/download/v/yq_linux_amd64
    type: binary
    override: False
    strip: None
    inBin: False
    latest: 4.34.2
    versions:
      - version: 4.34.2